
level = 0  # (int) The level of the location. This will determine if a user is allowed to use the location. Example: A user with Begging level 0 can't use a level 1 location.
id = "BRIDGE"  # (UPPER_SNAKE_CASE) The ID of the location.
name = "Under a Bridge"  # (string) The name of the location. This will appeal as the label in a select menu.
description = "Lmao homeless lookin ass 😆"  # (string) The description of the location. This will appear as the description in a select menu.
emoji = "<:PP_BEG:879382346812489809>"  # (string) The emoji that will be used to represent the location. Can also be custom disco emoji, E.g. "<custom_emoji:123456789>"

[[loot_table]]
    id = "ROTTEN_WOOD"  # (UPPER_SNAKE_CASE) The ID of an item in the loot table. Must be unique for all items in the [[locations.loot_table]] array.
    drop_rate = 0.05  # (float) The drop rate of the item. This is the chance that the item will be dropped. This example shows a 50% chance of dropping the item.
    min = 1  # (int) The minimum amount of the item that can be dropped.
    max = 5  # (int) The maximum number of this item that can be dropped from this location.

[[loot_table]]
    id = "GUITAR"  # (UPPER_SNAKE_CASE) The ID of an item in the loot table. Must be unique for all items in the [[locations.loot_table]] array.
    drop_rate = 0.01  # (float) The drop rate of the item. This is the chance that the item will be dropped. This example shows a 50% chance of dropping the item.
    min = 1  # (int) The minimum amount of the item that can be dropped.
    max = 2  # (int) The maximum number of this item that can be dropped from this location.

[[loot_table]]
    id = "SCRAP_METAL"  # (UPPER_SNAKE_CASE) The ID of an item in the loot table. Must be unique for all items in the [[locations.loot_table]] array.
    drop_rate = 0.05  # (float) The drop rate of the item. This is the chance that the item will be dropped. This example shows a 50% chance of dropping the item.
    min = 1  # (int) The minimum amount of the item that can be dropped.
    max = 5  # (int) The maximum number of this item that can be dropped from this location.

[[loot_table]]
    id = "METAL_INGOT"  # (UPPER_SNAKE_CASE) The ID of an item in the loot table. Must be unique for all items in the [[locations.loot_table]] array.
    drop_rate = 0.05  # (float) The drop rate of the item. This is the chance that the item will be dropped. This example shows a 50% chance of dropping the item.
    min = 1  # (int) The minimum amount of the item that can be dropped.
    max = 3  # (int) The maximum number of this item that can be dropped from this location.

[[loot_table]]
    id = "METH_PIPE"  # (UPPER_SNAKE_CASE) The ID of an item in the loot table. Must be unique for all items in the [[locations.loot_table]] array.
    drop_rate = 0.05  # (float) The drop rate of the item. This is the chance that the item will be dropped. This example shows a 50% chance of dropping the item.
    min = 1  # (int) The minimum amount of the item that can be dropped.
    max = 5  # (int) The maximum number of this item that can be dropped from this location.

[[loot_table]]
    id = "METH_POTION"  # (UPPER_SNAKE_CASE) The ID of an item in the loot table. Must be unique for all items in the [[locations.loot_table]] array.
    drop_rate = 0.01  # (float) The drop rate of the item. This is the chance that the item will be dropped. This example shows a 50% chance of dropping the item.
    min = 1  # (int) The minimum amount of the item that can be dropped.
    max = 2  # (int) The maximum number of this item that can be dropped from this location.

[[loot_table]]
    id = "CHEETOS"  # (UPPER_SNAKE_CASE) The ID of an item in the loot table. Must be unique for all items in the [[locations.loot_table]] array.
    drop_rate = 0.05  # (float) The drop rate of the item. This is the chance that the item will be dropped. This example shows a 50% chance of dropping the item.
    min = 3  # (int) The minimum amount of the item that can be dropped.
    max = 6  # (int) The maximum number of this item that can be dropped from this location.

[[loot_table]]
    id = "OLD_CLOTHES"  # (UPPER_SNAKE_CASE) The ID of an item in the loot table. Must be unique for all items in the [[locations.loot_table]] array.
    drop_rate = 0.05  # (float) The drop rate of the item. This is the chance that the item will be dropped. This example shows a 50% chance of dropping the item.
    min = 1  # (int) The minimum amount of the item that can be dropped.
    max = 3  # (int) The maximum number of this item that can be dropped from this location.

[[loot_table]]
    id = "CASHMERE"  # (UPPER_SNAKE_CASE) The ID of an item in the loot table. Must be unique for all items in the [[locations.loot_table]] array.
    drop_rate = 0.01  # (float) The drop rate of the item. This is the chance that the item will be dropped. This example shows a 50% chance of dropping the item.
    min = 1  # (int) The minimum amount of the item that can be dropped.
    max = 3  # (int) The maximum number of this item that can be dropped from this location.

# The quotes for the location.
[quotes]

    # (array) The default success quotes for the location. {} is a placeholder for whatever reward the user receives.
    success = [
        "aight kuh here's {}",  # how a user might see this: "Sure, here's 4 **Rotten Wood**s. Have a good day!"
        "take {}, and eat it, you little dumpster boy",
        "aight buddy here's {}",
        "ugh beggars are so annoying. here's {}, now stop wasting my time",
        "eh, you can have {}, I don't need that stuff anyways",
    ]

    # (array) The default failure quotes for the location.
    fail = [
        "nah 🅱️",
        "gtfo beggar",
        "nah I'm broke",
        "ew dont talk to me",
        "I'm not giving you anything, you look weird",
        "lmao poor",
        "eeeewwww don't touch me I'm too good for you",
        "ew poor",
        "don't touch my pp",
        "my wife has a bigger pp than you",
        "broke ass bitch",
        "cringe poor",
        "beg harder",
        "poor people make me scared",
        "dont touch me poor person",
        "get a job",
        "im offended",
        "no u",
        "i dont speak poor",
        "you should take a shower",
        "i love my wife... i love my wife... i love my wife..",
        "drink some water",
        "begone beggar",
        "No.",
        "no wtf?",
        "try being a little 'cooler' next time",
    ]

    # The mini-games for the user to complete.
    [quotes.minigames]

        # All quotes for the fill-in-the-blank mini-game.
        [quotes.minigames.fill_in_the_blank]

            approacher = "local crackhead"  # (string) The person approaching the user in this mini-game.
            context = "Some random crackhead points at you and starts yelling."  # (string) The context of the mini-game.
            success = "io mtae yoju got some crystal dfor me eh? alrigbht cheers hhers {}"  # (string) The success message for the user. E.g. "gameshow host: 'Good job! You win!'"
            fail = "woh are you?? gmet ouet of my hsuoe tyou fucking tory"  # (string) The failure message for the user. E.g. "gameshow host: 'Sorry, you lose!'"

        # All quotes for the scramble mini-game.
        [quotes.minigames.scramble]

            approacher = "scrambled text" # (string) The thing containing the scrambled text.
            context = "Some rich guy gives you a letter with scrambled text on it. If you unscramble it, you get a big reward." # (string) The context of the mini-game.

        # All quotes for the scramble mini-game.
        [quotes.minigames.retype]

            context = "Some rich guys notices you begging and laughs at you. If you make him feel bad for you, you can get some free stuff!" # (string) The context of the mini-game.
            