id = "METH_POTION"  # (UPPER_SNAKE_CASE) The ID of the item. Must be unique for all items in the [[items]] array.
type = "POTION"  # (UPPER_SNAKE_CASE) The type of the item.
rarity = "RARE" # (UPPER_SNAKE_CASE) The rarity of the item.
emoji = 880208473135144991  # (int) The custom ID of the emoji associated with the item.
name = "crystal potion"  # (string) The name of the item.
description = "Crystal meth, but in a bottle. Ride the ice pony without smoking! Rated 9.4/10 by many homeless people. “Mama loves her sweet shabu shabu, and this hot crystaline is the top of the white crystal crunch mountain. We call it getting gakked up on woop chicken.” — Proud customer." # (string) The description of the item.

# (array) Represents the skill requirements for a given item.
[[skill_requirements]]
    id = "BEGGING"  # (UPPER_SNAKE_CASE) The ID of the required skill. Must be unique for all skills in the [[skill_requirements]] array.
    level = 5  # (int) The level of the skill required.

# Represents the shop settings. I.e. the price, if it's buyable, if it's auctionable, etc.
[shop_settings]
    auctionable = true # (bool) Whether the item can be put up for auction.
    buyable = false  # (bool) Whether the item can be bought from the shop.
    buy = 50000  # (int): The price of the item when bought from the shop.
    sell = 18750  # (int): The price of the item when sold to the shop.

#  (array) The recipes of the item.
[[recipe]]
    id = "METH_PIPE"  # (string UPPER_SNAKE_CASE) The ID of an item that is required to craft this item. Must be unique for all items in the [[recipe]] array.
    amount = 25  # (int) The amount of the parent item required to craft said item.

# The usage of an item.
[usage]

    # (array) Represents thr crafting recipes involving the parent item.
    [[usage.crafting]]
        id = "METH_GUITAR"  # (UPPER_SNAKE_CASE) The ID of an item craftable with the parent item. Must be unique for all items in the [[usage.crafting]] array.
        amount = 1  # (int) The amount of the parent item required to craft said item.

    # (array) Represents the brewing recipes involving the parent item.
    [[usage.brewing]]
        # None


    # (array) Represents the skills that the parent item is used for.
    [[usage.skills]]
        id = "BEGGING"  # (UPPER_SNAKE_CASE) The ID of the skill that the parent item is used for. Must be unique for all skills in the [[usage.skills]] array.
