id = "METH_PIPE"  # (UPPER_SNAKE_CASE) The ID of the item. Must be unique for all items in the [[items]] array.
type = "CRAFTING REAGENT"  # (UPPER_SNAKE_CASE) The type of the item.
rarity = "UNCOMMON" # (UPPER_SNAKE_CASE) The rarity of the item.
emoji = 123456789  # (int) The custom ID of the emoji associated with the item.
name = "Item name"  # (string) The name of the item.
description = "Some crackhead left this behind." # (string) The description of the item.

# (array) Represents the skill requirements for a given item.
[[items.skill_requirements]]
    # None

# Represents the shop settings. I.e. the price, if it's buyable, if it's auctionable, etc.
[items.shop_settings]
    auctionable = false # (bool) Whether the item can be put up for auction.
    buyable = false  # (bool) Whether the item can be bought from the shop.
    buy = 2000  # (int): The price of the item when bought from the shop.
    sell = 750  # (int): The price of the item when sold to the shop.

#  (array) The recipes of the item.
[[items.recipe]]
    # None

# The usage of an item.
[items.usage]

    # (array) Represents thr crafting recipes involving the parent item.
    [[items.usage.crafting]]
        # None

    # (array) Represents the brewing recipes involving the parent item.
    [[items.usage.brewing]]
        id = "METH_POTION"  # (UPPER_SNAKE_CASE) The ID of a potion or beverage craftable with the parent item. Must be unique for all items in the [[items.usage.brewing]] array.
        amount = 25  # (int) The amount of the parent item required to brew said potion or beverage.

    # (array) Represents the skills that the parent item is used for.
    [[items.usage.skills]]
        # None
