[quotes]
failure = [
    "Ew poor person, step away from me please. I need to wash my hands now",
    "Don't touch my pp you freak, what do think you're doing???",
    "My wife has a bigger pp than you I'm not giving you shit",
    "I'm not donating to someone with such a tiny pp oh my god please go away",
    "Cringe tiny pp",
    "beg harder daddy",
    "People with a small pp make me scared",
    "Don't touch me poor person",
    "Get a job",
    "Oh my.. Did you really just beg for my pp? I'm offended" ,
    "No you",
    "I don't speak poor",
    "You should take a shower",
    "I love my wife... I love my wife... I love my wife..",
    "Hey, it's important to stay hydrated. Drink some water mate, love you",
    "Begone beggar",
    "No.",
    "Oh hell nah I'm not giving you my inches",
    "Try being a little 'cooler' next time",
    "Get the fuck out of my sight",
    "I'm not giving you anything mate",
]

success = [ # {0} = reward
    "Your pp is so small I feel bad, take {0}, now go away",
    "Yeah whatever mate take {0}",
    "You're so annoying, here, have {0}. Now scram! Skedaddle!",
    "Eh why not, here's {0}. Have a nice day",
    "Here's {0}, go buy yourself something nice"
]

[[locations]]
    level = 0
    id = "BRIDGE"
    emoji = "😔"
    name = "Under a Bridge"
    description = "Lmao broke boy go beg with the other homeless"

    [locations.quotes]
        fail = [
            "Damn bro I live under a bridge and you're asking ME for inches??",
            "What did you think was gonna happen when you asked some homeless dude for inches",
            "Sorry I spent all my inches on meth",
        ]

        [locations.quotes.minigames]

            [locations.quotes.minigames.fillintheblank]
                context = "While you're begging bypassers to give you inches, you notice a homeless guy high on meth. He's trying to tell you something, but you can't make out what he's saying."
                success = "Man I'm high as fuck, I think I'ma pass out. You can keep my stuff, {0}, incase I die"
                fail = "The meth addicted looks cries and runs away. You have no idea what just happened."



[[locations]]
    level = 1
    id = "MARKET"
    emoji = "🧑‍🌾"
    name = "Farmer's Market"
    description = "Yeehaw"

    [locations.quotes]
        fail = [
            "Step aside silly beggar, I have vegetables to sell",
            "I'm trying to sell my vegetables stop bothering me",
            "Please just let me sell my fruits in peace",
        ]

        [locations.quotes.minigames]

            [locations.quotes.minigames.fillintheblank]
                context = "You hear a farmer screaming at you in the distance. You can't quite figure out what he's saying"
                success = "Hey asshole! You left {0} behind!"
                fail = "Listen to me when I'm talking to you, dipshit! I was gonna give you a reward, but I think I'll keep it"

[[locations]]
    level = 2
    id = "BLOCK"
    emoji = "🏙️"
    name = "City Block"
    description = "I'm sure the residents have some inches to spare"

    [locations.quotes]
        fail = [
            "I'm so sick of this shit. I spend 4.050 inches a month on rent and can't afford food. Fuck you, you aren't getting anything",
            "Get off my block",
            "Oh go to hell",
        ]

        [locations.quotes.minigames]

            [locations.quotes.minigames.fillintheblank]
                context = "Some guy dressed in a dumbass spiderman costume runs up you and tells you something, but his mask is muffling his speech"
                success = "Hey asshole! You left {0} behind!"
                fail = "I asked you if you wanted to take a picture, fuckwit! Are you deaf?"

[[locations]]
    level = 3
    id = "CLUB"
    emoji = "<a:poledance:870466180253618196>"
    name = "Adult dance club"
    description = "Kids, look away!"

    [locations.quotes]
        fail = [
            "Just because I don't have clothes on doesn't mean you can just steal my pp",
            "I expect a good show before I give you anything",
        ]

        [locations.quotes.minigames]

            [locations.quotes.minigames.fillintheblank]
                context = "A gameshow host approaches you with a question"
                success = "Congratulations! You win {0}. Have a nice day!"
                fail = "Haha, you failed, fuckwit! Better luck next time!"


[[locations]]
    level = 4
    id = "AUCTION"
    emoji = "🖼️"
    name = "Art Auction"
    description = "It reeks of tax fraud"

    [locations.quotes]
        fail = [
            "Oh my god get away from me, I'm WAY too rich to talk to you",
            "My dog only drinks bottled water",
            "Do you know who I am!? I have money! I'm important! Get away from me!",
            "Stop asking for handouts, I never got help from anyone",
            "I don't even have any inches! I replaced my pp with gold!",
            "I don't have any inches to spare, I only have a few billion left. Hey, you know what's a good idea? Your kids should WORK for my kids!",
            "Oh please, I'm broke! The gas to fly my private jet is getting expensive",
            "GET THE FUCK OUT LMAO. I'M RICH, BITCH!",
            "You're wasting your time. Go do poor people things, like paying taxes",
            "I refuse to donate to someone with a house worth less than 10 million USD",
            "Ew, you're way too poor! I'm gonna go buy a new Bugatti, I'm getting tired of this Mercedes",
        ]

        [locations.quotes.minigames]

            [locations.quotes.minigames.fillintheblank]
                context = "A gameshow host approaches you with a question"
                success = "Congratulations! You win {0}. Have a nice day!"
                fail = "Haha, you failed, fuckwit! Better luck next time!"

[[locations]]
    level = 5
    id = "PUB"
    emoji = "🍺"
    name = "Uncle Joe's Pub"
    description = "Hope he doesn't touch me"

    [locations.quotes]
        fail = [
            "Buy me a drink first",
            "I just spent all my money on alcohol, sorry",
        ]

        [locations.quotes.minigames]

            [locations.quotes.minigames.fillintheblank]
                context = "Uncle joe approaches you. You can tell that he's extremely"
                success = "Congratulations! You win {0}. Have a nice day!"
                fail = "Haha, you failed, fuckwit! Better luck next time!"

[[locations]]
    level = 6
    id = "PARENTS"
    emoji = "👪"
    name = "Your parents"
    description = "They're extremely disappointed"

    [locations.quotes]
        fail = [
            "I'm disappointed in you",
            "This is why you aren't our favourite child",
            "Dont make me pull out the belt you little shit",
            "If your dad just bought condoms this would've never happened",
        ]

        [locations.quotes.minigames]

            [locations.quotes.minigames.fillintheblank]
                context = "Your parents are arguing in the hallway (It's probably your fault <:sadge:875296391163969567>) Your dad is yelling at your mom, try to figure out what he's saying"
                success = "Thank you for stopping dad from hitting me, I'm so sorry you have to go through this. Here's your monthly allowance: {0}"
                fail = "Haha, you failed, fuckwit! Better luck next time!"

[[locations]]
    level = 7
    id = "SCHOOL"
    emoji = "🏢"
    name = "At school"
    description = "Maybe Mr. McKno will donate inches, wink wonk"

    [locations.quotes]
        fail = [
            "Go learn instead of asking for inches smh",
            "Not right now sweetheart, I'm busy growing my pp",
        ]

        [locations.quotes.minigames]

            [locations.quotes.minigames.fillintheblank]
                context = "Some guy in the back of the class is screaming at the teacher. What is he saying?"
                success = "My life sucks anyways I have {0} for you"
                fail = "Christ your slow, I should bully you more often"

[[locations]]
    level = 8
    id = "FURRY"
    emoji = "<:uwu:872504680331227136>"
    name = "Furry Roleplay Server"
    description = "BLEACH MY EYES"

    [locations.quotes]
        fail = [
            "Rawr ~x3 \\*nuzzles\\* pounces on you - uwu u so warm<:uwu:872504680331227136>",
            "NYAH OwO \\*nuzzles your buldgywuldgy\\* sowwy queen but I hawve no inchy-winchies to spare👉👈😩",
        ]

        [locations.quotes.minigames]

            [locations.quotes.minigames.fillintheblank]
                context = "A 40 year old neckbeard starts petting you and calls you his 'little kitten'. He then proceeds to bark at you, but you can't understand what he's saying."
                success = "OwO daddy \\*nuts in pants\\* I brought you {0}. Pwease adopt me UwU"
                fail = ">:3 you weren't fast enough DADDY.. No rewards for youuu owowowowo UwU"