[[items]]
    id = "ITEM_ID"  # (UPPER_SNAKE_CASE) The ID of the item. Must be unique for all items in the [[items]] array.
    type = "TYPE" # (UPPER_SNAKE_CASE) The type of the item.
    rarity = "COMMON" # (UPPER_SNAKE_CASE) The rarity of the item.
    emoji = 123456789  # (int or string) The custom ID of the emoji associated with the item.
    name = "Item name"  # (string) The name of the item.
    description = "This is the description of the item" # The description of the item (string).

    [[items.skill_requirements]]  # (array) Represents the skill requirements for a given item.
        id = "SKILL_ID"  # (UPPER_SNAKE_CASE) The ID of the required skill. Must be unique for all skills in the [[items.skill_requirements]] array.
        level = 69  # (int) The level of the skill required.

    [items.shop_settings]  # Represents the shop settings. I.e. the price, if it's buyable, if it's auctionable, etc.
        auctionable = false # (bool) Whether the item can be put up for auction.
        buyable = true  # (bool) Whether the item can be bought from the shop.
        buy = 100  # (int): The price of the item when bought from the shop.
        sell = 20  # (int): The price of the item when sold to the shop.
    
    [[items.recipe]]  # (array) The recipes of the item.
        id = "REQUIRED_ITEM_ID"  # The ID of an item that is required to craft this item. Must be unique for all items in the [[items.recipe]] array (UPPER_SNAKE_CASE).
        amount = 10  # (int) The amount of the parent item required to craft said item.
    
    [items.usage]  # (array) the usage of an item.

        [[items.usage.crafting]]  # (array) Represents a crafting recipe involving the parent item.
            id = "CRAFTING_ITEM_ID"  # (UPPER_SNAKE_CASE) The ID of an item craftable with the parent item. Must be unique for all items in the [[items.usage.crafting]] array.
            amount = 69  # (int) The amount of the parent item required to craft said item.

        [[items.usage.brewing]]  # (array) Represents a brewing recipe involving the parent item.
            id = "POTION_OR_BEVERAGE_ID"  # (UPPER_SNAKE_CASE) The ID of a potion or beverage craftable with the parent item. Must be unique for all items in the [[items.usage.brewing]] array.
            amount = 69  # (int) The amount of the parent item required to brew said potion or beverage.

        [[items.usage.skills]]  # (array) Represents a skill that the parent item is used for.
            id = "SKILL_ID"  # (UPPER_SNAKE_CASE) The ID of the skill that the parent item is used for. Must be unique for all skills in the [[items.usage.skills]] array.
