[[items]]
    id = "ROTTEN_WOOD" # The ID of the item. Must be unique for all items in the [[items]] array (UPPER_SNAKE_CASE).
    type = "CRAFTING" # The type of the item (UPPER_SNAKE_CASE).
    rarity = "COMMON" # The rarity of the item (UPPER_SNAKE_CASE).
    emoji = 876433964749963274 # The custom ID of the emoji associated with the item (int).
    name = "Rotten Wood" # The name of the item (string).
    description = "A chunk of wood that has been rotted from a tree" # The description of the item (string).

    [[items.skill_requirements]] # The skill requirements of the item (array).
        # None

    [items.shop_settings] # The shop settings of the item.
        buyable = true # If the item can be bought from the shop (boolean).
        buy = 500 # The price of the item when bought from the shop (int).
        sell = 200 # The price of the item when sold to the shop (int).

        auctionable = false # If the item can be auctioned (boolean).
    
    [[items.recipe]] # The recipes of the item (array).
        # None
    
    [items.usage] # The usage of the item.

        [[items.usage.crafting]] # The crafting recipes involving the item (array).
            id = "GUITAR" # The ID of an item craftable with the item. Must be unique for all items in the [[items.usage.crafting]] array (UPPER_SNAKE_CASE).
            amount = 5 # The amount of the item required to craft this item (int).

        [[items.usage.brewing]] # The brewing recipes involving the item (array).
            # None

        [[items.usage.skills]] # The skills that this item is used for (array).
            # None

[[items]]
    id = "GUITAR" # The ID of the item. Must be unique for all items in the [[items]] array (UPPER_SNAKE_CASE).
    type = "TOOL" # The type of the item (UPPER_SNAKE_CASE).
    rarity = "UNCOMMON" # The rarity of the item (UPPER_SNAKE_CASE).
    emoji = 876864767728431124 # The custom ID of the emoji associated with the item (int).
    name = "Funky guitar" # The name of the item (string).
    description = "Looks pretty dope, you can use this shit to impress the people while begging." # The description of the item (string).

    [[items.skill_requirements]] # The skill requirements of the item (array).
        id = "BEGGING" # The ID of the skill required. Must be unique for all skills in the [[items.skill_requirements]] array (UPPER_SNAKE_CASE).
        level = 3 # The level of the skill required.

    [items.shop_settings] # The shop settings of the item.
        buyable = true # If the item can be bought from the shop (boolean).
        buy = 5000 # The price of the item when bought from the shop (int).
        sell = 1000 # The price of the item when sold to the shop (int).

        auctionable = true # If the item can be auctioned (boolean).
    
    [[items.recipe]] # The recipes of the item (array).
        id = "ROTTEN_WOOD" # The ID of an item that is required to craft this item. Must be unique for all items in the [[items.recipe]] array (UPPER_SNAKE_CASE).
        amount = 5 # The amount of the item required to craft this item (int).
    
    [items.usage] # The usage of the item.

        [[items.usage.crafting]] # The crafting recipes involving the item (array).
            # None

        [[items.usage.brewing]] # The brewing recipes involving the item (array).
            # None
        
        [[items.usage.skills]] # The skills that this item is used for (array).
            id = "BEGGING" # The ID of the skill that the item is used for. Must be unique for all skills in the [[items.usage.skills]] array (UPPER_SNAKE_CASE).
