[[locations]]
    level = 0  # (int) The level of the location. This will determine if a user is allowed to use the location. Example: A user with Begging level 0 can't use a level 1 location.
    id = "EXAMPLE_LOCATION"  # (UPPER_SNAKE_CASE) The ID of the location.
    name = "Example Location"  # (string) The name of the location. This will appeal as the label in a select menu.
    description = "This is an example location"  # (string) The description of the location. This will appear as the description in a select menu.
    emoji = "🥰"  # (string) The emoji that will be used to represent the location. Can also be custom disco emoji, E.g. "<custom_emoji:123456789>"

    [[locations.loot_table]]
        id = "EXAMPLE_LOOT_TABLE"  # (UPPER_SNAKE_CASE) The ID of an item in the loot table. Must be unique for all items in the [[locations.loot_table]] array.
        weight = 1.0  # (float) The weight of the item in the loot table. A higher weight means the item will be more likely to be chosen or chosen multiple times.
        limit = 5  # (int) The maximum number of this item that can be dropped from this location.
    
    # The quotes for the location.
    [locations.quotes]

        # (array) The default success quotes for the location. {0} is a placeholder for whatever reward the user receives.
        success = [
            "Sure, here's {0}. Have a good day!",  # how a user might see this: "Sure, here's 4 **Rotten Wood**s. Have a good day!"
            "oh, good timing! I have {0} for you",
            "Here you go, {0}",
            "Eh, you can have {0}, I don't need that stuff anyways",
        ]

        # (array) The default failure quotes for the location.
        fail = [
            "I'm sorry, I can't do that",
            "I don't have any inches to give you",
            "I'm broke, sorry",
            "I'm not sure I can do that",
        ]

        # Specific quotes for specific mini-games.
        [locations.quotes.minigames]

            # All quotes for the fill-in-the-blank mini-game.
            [locations.quotes.minigames.fillintheblank]

                approacher = "gameshow host"  # (string) The person approaching the user in this mini-game.
                context = "A gameshow host approaches you with a question"  # The context leading up to the event.
                success = "Good job! You win!"  # (string) The success message for the user. E.g. "gameshow host: 'Good job! You win!'"
                fail = "Sorry, you lose!"  # (string) The failure message for the user. E.g. "gameshow host: 'Sorry, you lose!'"
