# (array) The default success quotes. {} is a placeholder for whatever reward the user receives.
success = [
    "aight kuh here's {}",  # how a user might see this: "Sure, here's 4 **Rotten Wood**s. Have a good day!"
    "take {}, and eat it, you little dumpster boy",
    "aight buddy here's {}",
    "ugh beggars are so annoying. here's {}, now stop wasting my time",
    "eh, you can have {}, I don't need that stuff anyways",
]

# (array) The default failure quotes for the location.
fail = [
    "nah 🅱️",
    "gtfo beggar",
    "nah I'm broke",
    "ew dont talk to me",
    "I'm not giving you anything, you look weird",
    "lmao poor",
    "eeeewwww don't touch me I'm too good for you",
    "ew poor",
    "don't touch my pp",
    "my wife has a bigger pp than you",
    "broke ass bitch",
    "cringe poor",
    "beg harder",
    "poor people make me scared",
    "dont touch me poor person",
    "get a job",
    "im offended",
    "no u",
    "i dont speak poor",
    "you should take a shower",
    "i love my wife... i love my wife... i love my wife..",
    "drink some water",
    "begone beggar",
    "No.",
    "no wtf?",
    "try being a little 'cooler' next time",
]
