# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "person/character"  # (string) The name of the donator
    icon_url = "https://example.com/image.png?size=256"  # (string) The URL of the donator's icon. Square size recommended.

    # Represents custom quotes for the donator.
    [custom_quotes]
        success = [  # (array) The success quotes for the donator.
            "Blah blah blah you gain {} blah blah",  # (string) The quote. Will be formatted with the reward.
            "AAAAAAAAA {} blah blah",  # (string) The quote. Will be formatted with the reward.
        ]
        fail = [  # (array) The fail quotes for the donator.
            "Fuck off I don't care",  # (string) The quote.
            "No, I'm not giving you anything",  # (string) The quote.
        ]
